#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N shallow
#PBS -N parallel
#PBS -j oe
set KMP_PLACE_THREADS=24c,4t
module load cs5220

cd $PBS_O_WORKDIR
./shallow -i dam_break -o dam_break.out
